behaviors:
  Pathfinder:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    keep_checkpoints: 5
    max_steps: 5.0e6
    time_horizon: 1000
    summary_freq: 10000
    threaded: true

#  Collider:
#    trainer_type: ppo
#    hyperparameters:
#      batch_size: 64
#      buffer_size: 12000
#      learning_rate: 0.001
#      beta: 0.001
#      epsilon: 0.2
#      lambd: 0.99
#      num_epoch: 5
#      learning_rate_schedule: linear
#    network_settings:
#      normalize: true
#      hidden_units: 64
#      num_layers: 3
#      vis_encode_type: simple
#    reward_signals:
#      extrinsic:
#        gamma: 0.99
#        strength: 1.0
#    keep_checkpoints: 20
#    max_steps: 10000000
#    time_horizon: 1000
#    summary_freq: 12000
#    threaded: true
